### ISSUE TITLE
dist and module name mismatch

### ISSUE THREAD

**Issue by abraxxa** [CPAN-Security/CPANSEC-Admin#2]
Installation of MetaCPAN::Client fails because your dist and module names don't match, see https://github.com/metacpan/metacpan-client/issues/118.
Please fix this asap to not make MetaCPAN::Client tests to fail and prevent its installation.
Thanks!

**Comment by mickeyn** [comment]
Just note that we can unblock MetaCPAN::Client if needed, but it's best to have it fixed from this end.

**Comment by abraxxa** [comment]
Thanks @mickeyn! This is currently blocking our CI pipeline.

**Comment by oalders** [comment]
@abraxxa I'm a bit busy today, but if you wanted to create a PR for this, we could ship it.

**Comment by mickeyn** [comment]
@oalders I'll fix that.

**Comment by mickeyn** [comment]
I released MetaCPAN::Client with a fix. @abraxxa that should fix your pipeline.

**Comment by oalders** [comment]
Thanks, @mickeyn! 🚀

**Comment by abraxxa** [comment]
Thanks @mickeyn! Your fix works! 👍🏻
